### PR TITLE
Python3 ddfacet

### LINKED ISSUE #15: Few python3 issues
Mostly to do with subprocess calls returning byte strings. PR to follow.

### PR DESCRIPTION
**Pull request by mhardcastle**
Fixes #15

### CODE REVIEW

**Comment by bennahugo** [comment]
Martin can you make this PR to cyriltasse/ddfacet instead for testing. This
is just the publish repo

**Comment by mhardcastle** [comment]
Yeah, wasn't sure how you wanted to handle it. The published version is the one I'm using, so seemed easiest to do the pr here. let me see if I can figure out a way of merging.

**Comment by bennahugo** [comment]
Push it with -u onto a new remote to cyriltasse/ddfacet

**Comment by mhardcastle** [comment]
Fixed with git cherry-pick . Closing this PR.

**Comment by bennahugo** [comment]
Thanks Martin. Appreciated. I will approve for testing once I get back
home.

**Comment by bindatype** [comment]
Hi, is there a version of DDFacet that is compatible with Python 3? It seems that https://github.com/cyriltasse/DDFacet.git/ is password protected and I don't have access. I am an administrator on a cluster and have been asked to install DDFacet but we can no longer support applications depending on Python 2.7 since its obsolescence.

**Comment by bennahugo** [comment]
Version 0.5.2 is already python 3 compatible. Simply pull it from Dockerhub

**Comment by bindatype** [comment]
This is a cluster environment. Docker isn't an option for us and singularity failed. We're trying to build this from conda but are open to other suggestions.

**Comment by bennahugo** [comment]
Conda may not work. You should try using virtualenv instread. Apart from
the Lofar beam everything should be pip installable. See the dockerfile for
a build example

**Pull request closed without merging**
